main: me.gravitinos.perms.bungee.BungeePerms
name: Perms
version: 1.0
author: Gravitinos
description: Permissions Plugin by Gravitinos
commands:
  tr:
    description: Permissions main command
    usage: /<command>