main: me.gravitinos.perms.spigot.SpigotPerms
name: Perms
version: 1.0
author: Gravitinos
description: Permissions Plugin by Gravitinos
softdepend: [PlaceholderAPI]
commands:
  tr:
    description: Permissions main command
    usage: /<command>