main: me.gravitinos.perms.spigot.SpigotPerms
name: SoraxusPerms
version: 2.0
author: Gravitinos
description: Permissions Plugin by Gravitinos
softdepend: [PlaceholderAPI]
commands:
  ranks:
    description: Permissions main command
    usage: /<command>